[2025-05-23T20:49:31.219+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_delays_dag.extract_data scheduled__2025-05-11T00:00:00+00:00 [queued]>
[2025-05-23T20:49:31.223+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_delays_dag.extract_data scheduled__2025-05-11T00:00:00+00:00 [queued]>
[2025-05-23T20:49:31.223+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-05-23T20:49:31.290+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_data> on 2025-05-11 00:00:00+00:00
[2025-05-23T20:49:31.293+0000] {standard_task_runner.py:57} INFO - Started process 430 to run task
[2025-05-23T20:49:31.295+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'train_delays_dag', 'extract_data', 'scheduled__2025-05-11T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/train_delays_dag.py', '--cfg-path', '/tmp/tmpkjk70nf2']
[2025-05-23T20:49:31.296+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask extract_data
[2025-05-23T20:49:31.306+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-23T20:49:31.329+0000] {task_command.py:415} INFO - Running <TaskInstance: train_delays_dag.extract_data scheduled__2025-05-11T00:00:00+00:00 [running]> on host 9541251e9700
[2025-05-23T20:49:31.387+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='train_delays_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-11T00:00:00+00:00'
[2025-05-23T20:49:31.388+0000] {logging_mixin.py:151} INFO - Downloading train_delays.csv...
[2025-05-23T20:49:31.493+0000] {logging_mixin.py:151} INFO - Error downloading train_delays.csv: 404 Client Error: Not Found for url: https://dataportal.orr.gov.uk/statistics/table-3184.csv
[2025-05-23T20:49:31.494+0000] {logging_mixin.py:151} INFO - Downloading cancellations.csv...
[2025-05-23T20:49:34.334+0000] {logging_mixin.py:151} INFO - Error downloading cancellations.csv: 404 Client Error: Not Found for url: https://dataportal.orr.gov.uk/media/3024/table-3124.csv
[2025-05-23T20:49:34.337+0000] {logging_mixin.py:151} INFO - Downloading punctuality.csv...
[2025-05-23T20:49:34.475+0000] {logging_mixin.py:151} INFO - Error downloading punctuality.csv: 404 Client Error: Not Found for url: https://dataportal.orr.gov.uk/media/3025/table-3138.csv
[2025-05-23T20:49:34.478+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-23T20:49:34.498+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=train_delays_dag, task_id=extract_data, execution_date=20250511T000000, start_date=20250523T204931, end_date=20250523T204934
[2025-05-23T20:49:34.541+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-23T20:49:34.568+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-24T00:46:24.562+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_delays_dag.extract_data scheduled__2025-05-11T00:00:00+00:00 [queued]>
[2025-05-24T00:46:24.566+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_delays_dag.extract_data scheduled__2025-05-11T00:00:00+00:00 [queued]>
[2025-05-24T00:46:24.567+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-05-24T00:46:24.639+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_data> on 2025-05-11 00:00:00+00:00
[2025-05-24T00:46:24.642+0000] {standard_task_runner.py:57} INFO - Started process 1197 to run task
[2025-05-24T00:46:24.644+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_delays_dag', 'extract_data', 'scheduled__2025-05-11T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/train_delays_dag.py', '--cfg-path', '/tmp/tmp6gcyx__a']
[2025-05-24T00:46:24.647+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask extract_data
[2025-05-24T00:46:24.685+0000] {task_command.py:415} INFO - Running <TaskInstance: train_delays_dag.extract_data scheduled__2025-05-11T00:00:00+00:00 [running]> on host a5551f46ca35
[2025-05-24T00:46:24.734+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_delays_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-11T00:00:00+00:00'
[2025-05-24T00:46:24.735+0000] {logging_mixin.py:151} INFO - File data/raw/train_delays.csv already exists. Skipping download.
[2025-05-24T00:46:24.735+0000] {logging_mixin.py:151} INFO - File data/raw/cancellations.csv already exists. Skipping download.
[2025-05-24T00:46:24.735+0000] {logging_mixin.py:151} INFO - File data/raw/punctuality.csv already exists. Skipping download.
[2025-05-24T00:46:24.735+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-24T00:46:24.742+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=train_delays_dag, task_id=extract_data, execution_date=20250511T000000, start_date=20250524T004624, end_date=20250524T004624
[2025-05-24T00:46:24.782+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-24T00:46:24.800+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
