[2025-05-23T22:10:04.550+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cancellations_etl_dag.transform_data manual__2025-05-23T22:10:02.997538+00:00 [queued]>
[2025-05-23T22:10:04.555+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cancellations_etl_dag.transform_data manual__2025-05-23T22:10:02.997538+00:00 [queued]>
[2025-05-23T22:10:04.555+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-05-23T22:10:04.562+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform_data> on 2025-05-23 22:10:02.997538+00:00
[2025-05-23T22:10:04.565+0000] {standard_task_runner.py:57} INFO - Started process 207 to run task
[2025-05-23T22:10:04.568+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'cancellations_etl_dag', 'transform_data', 'manual__2025-05-23T22:10:02.997538+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/cancellations_etl_dag.py', '--cfg-path', '/tmp/tmpfv7xz6ur']
[2025-05-23T22:10:04.570+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask transform_data
[2025-05-23T22:10:04.584+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-23T22:10:04.609+0000] {task_command.py:415} INFO - Running <TaskInstance: cancellations_etl_dag.transform_data manual__2025-05-23T22:10:02.997538+00:00 [running]> on host b5b9d485c58a
[2025-05-23T22:10:04.797+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cancellations_etl_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-23T22:10:02.997538+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-23T22:10:02.997538+00:00'
[2025-05-23T22:10:04.813+0000] {logging_mixin.py:151} INFO - Columns in cancellation data: Index(['Textbox22', 'Textbox24', 'financial_period_key',
       'National_or_Operator', 'Trains_planned', 'Trains_part_cancelled1',
       'Trains_full_cancelled', 'Cancellation_score__number_',
       'NR_Responsible_infrastructure', 'NR_responsible_external_Event',
       'TOC_responsible_TOC_fault', 'TOC_responsible_external_event',
       'Percent_cancelled_periodic', 'Percent_cancelled_periodic__MAA_'],
      dtype='object')
[2025-05-23T22:10:04.822+0000] {logging_mixin.py:151} INFO -                                        Textbox22  ... Percent_cancelled_periodic__MAA_
0  Periodic cancellations score \r\n(percentage)  ...                              [z]
1  Periodic cancellations score \r\n(percentage)  ...                              [z]
2  Periodic cancellations score \r\n(percentage)  ...                              [z]
3  Periodic cancellations score \r\n(percentage)  ...                              [z]
4  Periodic cancellations score \r\n(percentage)  ...                              [z]

[5 rows x 14 columns]
[2025-05-23T22:10:04.836+0000] {logging_mixin.py:151} INFO - Cleaned cancellation data saved to data/processed/cancellation_cleaned.csv
[2025-05-23T22:10:04.836+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-23T22:10:04.843+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=cancellations_etl_dag, task_id=transform_data, execution_date=20250523T221002, start_date=20250523T221004, end_date=20250523T221004
[2025-05-23T22:10:04.872+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-23T22:10:04.885+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
