[2025-05-23T20:49:35.009+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_delays_dag.transform_data scheduled__2025-05-11T00:00:00+00:00 [queued]>
[2025-05-23T20:49:35.015+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_delays_dag.transform_data scheduled__2025-05-11T00:00:00+00:00 [queued]>
[2025-05-23T20:49:35.016+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-05-23T20:49:35.090+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform_data> on 2025-05-11 00:00:00+00:00
[2025-05-23T20:49:35.094+0000] {standard_task_runner.py:57} INFO - Started process 436 to run task
[2025-05-23T20:49:35.096+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'train_delays_dag', 'transform_data', 'scheduled__2025-05-11T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/train_delays_dag.py', '--cfg-path', '/tmp/tmphl9znu57']
[2025-05-23T20:49:35.098+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask transform_data
[2025-05-23T20:49:35.108+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-23T20:49:35.132+0000] {task_command.py:415} INFO - Running <TaskInstance: train_delays_dag.transform_data scheduled__2025-05-11T00:00:00+00:00 [running]> on host 9541251e9700
[2025-05-23T20:49:35.181+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='train_delays_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-11T00:00:00+00:00'
[2025-05-23T20:49:35.181+0000] {logging_mixin.py:151} INFO - File data/raw/train_delays.csv does not exist. Please download the data first.
[2025-05-23T20:49:35.182+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-23T20:49:35.188+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=train_delays_dag, task_id=transform_data, execution_date=20250511T000000, start_date=20250523T204935, end_date=20250523T204935
[2025-05-23T20:49:35.235+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-23T20:49:35.250+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-24T00:46:25.346+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_delays_dag.transform_data scheduled__2025-05-11T00:00:00+00:00 [queued]>
[2025-05-24T00:46:25.351+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_delays_dag.transform_data scheduled__2025-05-11T00:00:00+00:00 [queued]>
[2025-05-24T00:46:25.351+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-05-24T00:46:25.425+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform_data> on 2025-05-11 00:00:00+00:00
[2025-05-24T00:46:25.428+0000] {standard_task_runner.py:57} INFO - Started process 1203 to run task
[2025-05-24T00:46:25.431+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_delays_dag', 'transform_data', 'scheduled__2025-05-11T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/train_delays_dag.py', '--cfg-path', '/tmp/tmpei291h5z']
[2025-05-24T00:46:25.433+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask transform_data
[2025-05-24T00:46:25.466+0000] {task_command.py:415} INFO - Running <TaskInstance: train_delays_dag.transform_data scheduled__2025-05-11T00:00:00+00:00 [running]> on host a5551f46ca35
[2025-05-24T00:46:25.515+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_delays_dag' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-11T00:00:00+00:00'
[2025-05-24T00:46:25.516+0000] {logging_mixin.py:151} INFO - Processing file: data/raw/train_delays.csv...
[2025-05-24T00:46:25.533+0000] {logging_mixin.py:151} INFO - Cleaned train delays data saved to data/processed/train_delays_cleaned.csv
[2025-05-24T00:46:25.533+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-24T00:46:25.540+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=train_delays_dag, task_id=transform_data, execution_date=20250511T000000, start_date=20250524T004625, end_date=20250524T004625
[2025-05-24T00:46:25.571+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-24T00:46:25.585+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
