[2025-05-23T20:49:30.801+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: punctuality_etl_dag.extract_data scheduled__2025-05-22T00:00:00+00:00 [queued]>
[2025-05-23T20:49:30.879+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: punctuality_etl_dag.extract_data scheduled__2025-05-22T00:00:00+00:00 [queued]>
[2025-05-23T20:49:30.880+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-05-23T20:49:30.889+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_data> on 2025-05-22 00:00:00+00:00
[2025-05-23T20:49:30.895+0000] {standard_task_runner.py:57} INFO - Started process 427 to run task
[2025-05-23T20:49:30.898+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'punctuality_etl_dag', 'extract_data', 'scheduled__2025-05-22T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/punctuality_etl_dag.py', '--cfg-path', '/tmp/tmpzun2nxq_']
[2025-05-23T20:49:30.904+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask extract_data
[2025-05-23T20:49:30.923+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-23T20:49:30.961+0000] {task_command.py:415} INFO - Running <TaskInstance: punctuality_etl_dag.extract_data scheduled__2025-05-22T00:00:00+00:00 [running]> on host 9541251e9700
[2025-05-23T20:49:31.033+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='punctuality_etl_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-22T00:00:00+00:00'
[2025-05-23T20:49:31.034+0000] {logging_mixin.py:151} INFO - Downloading train_delays.csv...
[2025-05-23T20:49:31.170+0000] {logging_mixin.py:151} INFO - Error downloading train_delays.csv: 404 Client Error: Not Found for url: https://dataportal.orr.gov.uk/statistics/table-3184.csv
[2025-05-23T20:49:31.171+0000] {logging_mixin.py:151} INFO - Downloading cancellations.csv...
[2025-05-23T20:49:34.335+0000] {logging_mixin.py:151} INFO - Error downloading cancellations.csv: 404 Client Error: Not Found for url: https://dataportal.orr.gov.uk/media/3024/table-3124.csv
[2025-05-23T20:49:34.337+0000] {logging_mixin.py:151} INFO - Downloading punctuality.csv...
[2025-05-23T20:49:34.473+0000] {logging_mixin.py:151} INFO - Error downloading punctuality.csv: 404 Client Error: Not Found for url: https://dataportal.orr.gov.uk/media/3025/table-3138.csv
[2025-05-23T20:49:34.475+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-23T20:49:34.495+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=punctuality_etl_dag, task_id=extract_data, execution_date=20250522T000000, start_date=20250523T204930, end_date=20250523T204934
[2025-05-23T20:49:34.538+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-23T20:49:34.562+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
